# Generated by Django 5.2.1 on 2026-02-28 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steno_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStegoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(help_text='SHA-256 Hash of the generated stego image', max_length=64, unique=True)),
                ('version', models.IntegerField(default=1, help_text='Steganography protocol version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_attempts', models.IntegerField(default=0)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_stego_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
