# Generated by Django 5.2.1 on 2026-05-03 09:19

import steno_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steno_app', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='otp',
            field=models.CharField(default=steno_app.models.generate_otp, max_length=6),
        ),
    ]
